version: 1
accounts:
  - name: alice
    mnemonic: "mix traffic rail bright utility aim traffic inform frost hungry output can glad object ability clog cable hospital slam cancel lucky real memory put"
    coins: ["20000upnte", "200000000stake"]
  - name: bob
    mnemonic: "mom decrease income scissors sheriff sand seminar narrow circle vote focus thing junior cross sweet mule social seminar spare nominee proof glare lunar you"
    coins: ["10000upnte", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5pnte", "100000stake"]
